Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LibraryFinal.Models;

public partial class User
{
    public Guid Id { get; set; }

    [Display(Name = "Nombre de usuario")]
    public string UserName { get; set; } = null!;

    public string Password { get; set; } = null!;
    [Display(Name = "Rol")]
    public string Role { get; set; } = null!;

    public virtual ICollection<Ownership> Ownerships { get; set; } = new List<Ownership>();
}

Controllers/OwnershipsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryFinal.Models;
using Microsoft.AspNetCore.Authorization;

namespace LibraryFinal.Controllers
{
    public class OwnershipsController : Controller
    {
        private readonly LibraryFinalContext _context;

        public OwnershipsController(LibraryFinalContext context)
        {
            _context = context;
        }

        // GET: Ownerships
        public async Task<IActionResult> Index()
        {
            var libraryFinalContext = _context.Ownerships.Include(o => o.Book).Include(o => o.User);
            return View(await libraryFinalContext.ToListAsync());
        }

        // GET: Ownerships/Details/5
        [Authorize]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ownership = await _context.Ownerships
                .Include(o => o.Book)
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ownership == null)
            {
                return NotFound();
            }

            return View(ownership);
        }

        // GET: Ownerships/Create
        [Authorize]
        public async Task<IActionResult> CreateAsync()
        {
            var books = await _context.Books.Select(b => new SelectListItem { Text = b.Title, Value = b.Id.ToString() }).ToListAsync();
            ViewBag.Books = books;

            var users = await _context.Users.Select(u => new SelectListItem { Text = u.UserName, Value = u.Id.ToString() }).ToListAsync();
            ViewBag.Users = users;

            return View();
        }

        // POST: Ownerships/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Policy = "AdminOnly")]
        public async Task<IActionResult> Create(Ownership ownership)
        {
            if (ModelState.IsValid)
            {
                ownership.Id = Guid.NewGuid(); // Genera un nuevo GUID para el Id
                _context.Add(ownership);
                try
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException ex)
                {
                    // Manejar las excepciones de integridad aquí
                    ModelState.AddModelError(string.Empty, "Error al guardar el ownership.");
                }
            }
            return View(ownership);
        }


        // GET: Ownerships/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ownership = await _context.Ownerships.FindAsync(id);
            if (ownership == null)
            {
                return NotFound();
            }
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Id", ownership.BookId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", ownership.UserId);
            return View(ownership);
        }

        // POST: Ownerships/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "AdminOnly")]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,UserId,BookId")] Ownership ownership)
        {
            if (id != ownership.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ownership);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OwnershipExists(ownership.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Id", ownership.BookId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", ownership.UserId);
            return View(ownership);
        }

        // GET: Ownerships/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ownership = await _context.Ownerships
                .Include(o => o.Book)
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ownership == null)
            {
                return NotFound();
            }

            return View(ownership);
        }

        // POST: Ownerships/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "AdminOnly")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var ownership = await _context.Ownerships.FindAsync(id);
            if (ownership != null)
            {
                _context.Ownerships.Remove(ownership);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OwnershipExists(Guid id)
        {
            return _context.Ownerships.Any(e => e.Id == id);
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryFinal.Models;
using Microsoft.AspNetCore.Authorization;

namespace LibraryFinal.Controllers
{
    public class UsersController : Controller
    {
        private readonly LibraryFinalContext _context;

        public UsersController(LibraryFinalContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        [Authorize]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "AdminOnly")]
        public async Task<IActionResult> Create([Bind("Id,UserName,Password,Role")] User user)
        {
            if (ModelState.IsValid)
            {
                user.Id = Guid.NewGuid(); // Genera un nuevo GUID para el Id
                Console.WriteLine(user);
                _context.Add(user);
                try
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException ex)
                {
                    // Manejar las excepciones de integridad aquí
                    ModelState.AddModelError(string.Empty, "Error al guardar el usuario.");
                }
            }
            return View(user);

        }

        // GET: Users/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "AdminOnly")]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,UserName,Password,Role")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "AdminOnly")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Search(string query)
        {
            var users = await _context.Users.Where(u => u.UserName.Contains(query)).ToListAsync();
            var options = users.Select(u => new SelectListItem { Text = u.UserName, Value = u.Id.ToString() });
            return Json(options);
        }


        private bool UserExists(Guid id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

Views/Users/Create.cshtml
@model User

<h1>Create</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control" />
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Users">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Users/Delete.cshtml
@model User

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Role)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" asp-controller="Users">Back to List</a>
    </form>
</div>

Views/Users/Details.cshtml
@model User

<h1>Details</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Role)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-controller="Users" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index" asp-controller="Users">Back to List</a>
</div>

Views/Users/Edit.cshtml
@model User

<h1>Edit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control" />
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Ownerships">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Users/Index.cshtml
@model List<User>

<h1>Index</h1>

<p>
    <a href="@Url.Action("Create", "Users")">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Nombre de Usuario
            </th>
            <th>
                Rol
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Role)
            </td>
            <td>
                <a asp-action="Edit" asp-controller="Users" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-controller="Users" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-controller="Users" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>